horaestudo=3
exercíciohora=5
dias=60
treinobimestral=horaestudo*exercíciohora*dias
nome='livio'
print(horaestudo)
print(exercíciohora)
print(dias)
print(treinobimestral)
print(nome)
numero1=14
numero2=5
numero3=3
resultado1=numero1+numero2
resultado2=numero2*numero3
resultado3=numero1-numero3
print(resultado1)
print(resultado2)
print(resultado3)
print(float(exercíciohora))
print(int(16.87))
print(str(treinobimestral))
'900'
